services:
  mc-panel:
    build: .
    volumes:
      - ./server:/server/server
      - ./config:/server/config
      - ./backups:/server/backups
    ports:
      - 1234:1234
      - 25565:25565/udp
    stop_signal: SIGINT
    stop_grace_period: "30s"